server:
  log_level: info

metrics:
  #wal_directory: /tmp/wal
  global:
    scrape_interval: 1m 
    remote_write:
      - url: http://prometheus:9090/api/v1/write
  configs:
    - name: default
      scrape_configs:
        - job_name: grafana-agent
          static_configs:
            - targets: ['127.0.0.1:12345']
        - job_name: apollo-router
          static_configs:
            - targets: ['apollo-router:9090']
        - job_name: bpmn-engine
          static_configs:
            - targets: ['bpmn-engine:8081']
        - job_name: libre-core
          static_configs:
            - targets: ['libre-core:4002']
        - job_name: libre-BaaS
          metrics_path: "/debug/prometheus_metrics"
          static_configs:
            - targets:
                - zero:6080     
                - alpha:8080
        - job_name: keycloak
          static_configs:
            - targets: ['keycloak:8080']
        - job_name: nats
          static_configs:
            - targets: ['prometheus-nats-exporter:7777'] 

        
logs:
  configs:
  - name: default
    scrape_configs:
      - job_name: docker_scrape 
        docker_sd_configs:
          - host: unix:///var/run/docker.sock
            refresh_interval: 5s
        relabel_configs:
          - source_labels: ['__meta_docker_container_name']
            regex: '/(.*)'
            target_label: 'container'
        pipeline_stages:
          - json:
              expressions:   ####### For fields section in Loki logs
                time: time
                message: message
                level: level
                trace_id: trace_id
                span_id: span_id
                job: job
          - labels:    ####### For Label Filters for searching Logs
              level:
          - timestamp:
              source: time
              format: RFC3339
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push


traces:
  configs:
  - name: default
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    remote_write:
      - endpoint: tempo:4317
        insecure: true
    batch:
      timeout: 5s
      send_batch_size: 100


integrations:
  node_exporter:
